### ISSUE TITLE
Does not work with Python 3.8 ?

### ISSUE THREAD

**Issue by noise23** [woodcoin-core/woodcoin-explorer#8]
Hello,

It seems like it does not work with Python 3.8 -
installed it on Ubuntu 20.04 server and abe fails at x_patt = re.compile(r"X\z") line in SqlAbstraction.py when trying initial load to empty db:

```
noise@ID1183:/usr/local/lib/python3.8/dist-packages/Abe# /usr/bin/python3 -m Abe.abe --config /users/noise/abe.conf  --commit-bytes 100000 --no-serve
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=4294967295
clob_type=LONGTEXT
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 1894, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 1888, in main
    store = make_store(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 151, in make_store
    store = DataStore.new(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 3404, in new
    return DataStore(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 170, in __init__
    store.initialize()
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 613, in initialize
    store.configure()
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 920, in configure
    config = store._sql.configure()
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 669, in configure
    sql.configure_binary_type()
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 687, in configure_binary_type
    sql._set_flavour()
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 143, in _set_flavour
    transform = sql._binary_as_hex(transform)
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 357, in _binary_as_hex
    x_patt = re.compile(r"X\z")
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.8/sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \z at position 1
```
I've tried to use regex instead of re replacing 'import re' with 'import regex as re' but then it fails with Exception: No known binary data representation works:

```
noise@ID1183:/usr/local/lib/python3.8/dist-packages/Abe# /usr/bin/python3 -m Abe.abe --config /users/noise/abe.conf  --commit-bytes 100000 --no-serve
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=4294967295
clob_type=LONGTEXT
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 1894, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 1888, in main
    store = make_store(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/abe.py", line 151, in make_store
    store = DataStore.new(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 3404, in new
    return DataStore(args)
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 170, in __init__
    store.initialize()
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 613, in initialize
    store.configure()
  File "/usr/local/lib/python3.8/dist-packages/Abe/DataStore.py", line 920, in configure
    config = store._sql.configure()
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 669, in configure
    sql.configure_binary_type()
  File "/usr/local/lib/python3.8/dist-packages/Abe/SqlAbstraction.py", line 692, in configure_binary_type
    raise Exception(
Exception: No known binary data representation works
```

Thank you!

**Comment by Lvl4Sword** [comment]
A new version of the explorer rewritten in Flask is being worked on, so keeping the Abe port up-to-date isn't as big of a priority right now.
I should have something new to show **soon**.
If you're not a part of the Woodcoin Discord/IRC, feel free to join ( available at https://woodcoin.org/#contact ).
An announcement will be made when the new explorer is ready.
